### ISSUE TITLE
感谢作者分享，反馈几个bug

### ISSUE THREAD

**Issue by kinghom** [wudifamo/Neleme#1]
1、sdk25 运行的时候右边recycleview顶部的类别条目看不到
2、在已选商品recycleview上下滑动的时候，背后的recycleview也会跟着滑动

**Comment by wudifamo** [comment]
1我改好了 
2是详情页吗

**Comment by kinghom** [comment]
测试了一下第二个问题，也是sdk25出现的，不是详情页，是购物车的已选商品那个popwindow，滚动这个popwindow里面的recycleview(选多几个商品来测试)，然后上下滑动，你留意一下背后的  协议只写饱饭阿斯顿飞 这个标题

**Comment by wudifamo** [comment]
2也改好了.给个Star亲

**Comment by kinghom** [comment]
好的，会给star的，你改了之后购物车列表出现滑动不了

**Comment by wudifamo** [comment]
刚提交再试试

**Comment by kinghom** [comment]
测试了一下  第二个问题还没有解决

**Comment by wudifamo** [comment]
我是用的25的模拟器一切正常啊

**Comment by kinghom** [comment]
可以了 应该是我的缓存问题 -.-！

**Comment by fengchuiyeluo** [comment]
请教下，购物车详情页滚动导致外层跟着滚动的解决思路是什么呢，demo不会，但我自己的就是会
